---
- name: playbook
  hosts: all
  become: yes
  tasks:
    - name: installe httpd....
      yum:
        name: httpd
        state: installed
      notify: start apache

  handlers:
    - name: start apache
      service:
        name: httpd
        state: started
      
