---
- name: playbook
  hosts: all
  tasks:
    - name: installe httpd....
      yum:
        name: httpd
        state: installed

    - name: start httpd...
      service:
        name: httpd
        state: started
      
