---
- name: p-b
  hosts: all
  become: yes
  vars_files:
  - user.yml 
  tasks: 
   - name: create user {{user1}}
     user:
       name: "{{user1}}"

   - name: create user {{user2}}
     user:
       name: "{{user2}}"

   - name: create user {{user3}}
     user:
       name: "{{user3}}"

    
