---
- name: onemore user
  hosts: webserver
  become: yes
  tasks:
    - name: creating mul- user
      user: name='{{ item }}' state=present
      with_items:
        - raju
        - buju
        - kaju
