---
# tasks file for setup-httpd-role
- name: install https.....
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: start httpd

- name: copy file
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0777

  
      
